/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LOGIN;

import java.awt.Desktop;
import conexionSQL.conexionSQL;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jlopezh47
 */
public class LOGIN extends javax.swing.JFrame {

    conexionSQL cc=new conexionSQL();
    Connection con=cc.conexion();

    /**
     * Creates new form ingreso1
     */
    public LOGIN() {
        initComponents();
        txtpass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        seglogo = new javax.swing.JLabel();
        iniciar = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        usuario1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        btningresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnadmin = new javax.swing.JButton();
        city = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        logo.setText("jLabel2");
        logo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logo.setMaximumSize(new java.awt.Dimension(71, 30));
        logo.setMinimumSize(new java.awt.Dimension(71, 30));
        logo.setPreferredSize(new java.awt.Dimension(171, 130));
        logo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                logoFocusGained(evt);
            }
        });
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, 150));

        seglogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Profile-pic.jpg"))); // NOI18N
        seglogo.setText("jLabel1");
        bg.add(seglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, 40));

        iniciar.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        iniciar.setText("iniciar sesion");
        bg.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, -1));

        usuario.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        usuario.setText("usuario");
        bg.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        bg.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 10));

        usuario1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        usuario1.setText("contraseña");
        bg.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtpass.setText("jPasswordField1");
        txtpass.setBorder(null);
        bg.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, -1));

        btningresar.setForeground(new java.awt.Color(0, 204, 255));
        btningresar.setText("INGRESAR");
        btningresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        bg.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 20));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("lorenzo matom");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        btnadmin.setText("CONF. ADMIN");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        bg.add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        city.setMaximumSize(new java.awt.Dimension(276, 480));
        city.setMinimumSize(new java.awt.Dimension(276, 480));
        bg.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 220, 297));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("josue lopez &");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_logoFocusGained

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
       
        ValidarUsuario();
        txtusuario.setText(null);
        txtpass.setText(null);

            
                                        

    }//GEN-LAST:event_btningresarActionPerformed

    public void ValidarUsuario(){
    
        int resultado=0;
        String pass=String.valueOf(txtpass.getPassword());
        String usuario=txtusuario.getText();
        String SQL = "select*from usuarios where usuario='"+usuario+"'and pass='"+pass+"'";
        
        
        
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            if(rs.next()){
                resultado=1;
                if(resultado==1){
                    this.dispose();
                    Desktop.getDesktop().browse(new URL( "file:///C:/Users/jlopezh47/Desktop/paginas/principal.html").toURI());
                    
                }
            }else{
             JOptionPane.showMessageDialog(null,"Error de acceso, usuario no registrado");   
            }
            
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error "+ e.getMessage());
        }
}
    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        // TODO add your handling code here:
          try {
            //codigo a ejecutar si no hay errores
            
            String usuario=txtusuario.getText(); 
            char[]contrasenia=txtpass.getPassword();
            //REALIZAMOS LA CONVERSION DE CHAR A STRING
            String clave=new String(contrasenia);
            if (usuario.equals("admin")&&(clave.equals("adminpass"))) {
            JOptionPane.showMessageDialog(null,"usuario autenticado, bienvenido :)"); 
            usuario1 b=new usuario1();
            b.setVisible(true);
            this.setVisible(false);
            
            
            }else{
                JOptionPane.showMessageDialog(null,"usuariof incorrecto, revise sus datos :("); 
                txtusuario.setText("");
                txtpass.setText("");
                txtusuario.requestFocus();
            }
            
        } catch (Exception e) {
            // cuando existe una excepcion
            System.out.println(e.getMessage());
        }
                             
         
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btningresar;
    private javax.swing.JLabel city;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel seglogo;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables
}
